name: "Ruby Test"

on: push

jobs:
  ruby_test:
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-ruby@v1
          with:
            ruby-version: '2.7'
        - run: bin/rails test
