jobs:
  ruby_test:
    name: 'Ruby Test'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: bundle install

    - name: Run Ruby tests
      run: bin/rails test
